//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EisenVaultOutlookPlugin {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UserInterfaceStrings_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserInterfaceStrings_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EisenVaultOutlookPlugin.UserInterfaceStrings-en", typeof(UserInterfaceStrings_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action settings changed.
        /// </summary>
        internal static string ActionSettinsChanged {
            get {
                return ResourceManager.GetString("ActionSettinsChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse Repositories and Select a Folder to Save Email In.
        /// </summary>
        internal static string BrowseFoldersSelectFolder {
            get {
                return ResourceManager.GetString("BrowseFoldersSelectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string btnConfig {
            get {
                return ResourceManager.GetString("btnConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Folder.
        /// </summary>
        internal static string btnCreate {
            get {
                return ResourceManager.GetString("btnCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save to Default Folder.
        /// </summary>
        internal static string btnUploadDefaultFolder {
            get {
                return ResourceManager.GetString("btnUploadDefaultFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save to Last Used Folder.
        /// </summary>
        internal static string btnUploadLastFolder {
            get {
                return ResourceManager.GetString("btnUploadLastFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default folder changed.
        /// </summary>
        internal static string DefaultFolderChanged {
            get {
                return ResourceManager.GetString("DefaultFolderChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The DefaultFolder has not been set correctly.
        /// </summary>
        internal static string DefaultFolderNotSetCorrectly {
            get {
                return ResourceManager.GetString("DefaultFolderNotSetCorrectly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while uploading file, Please try again!!.
        /// </summary>
        internal static string ErrorOnUpload {
            get {
                return ResourceManager.GetString("ErrorOnUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File(s) uploaded successfully.
        /// </summary>
        internal static string FilesUploadedSuccessfully {
            get {
                return ResourceManager.GetString("FilesUploadedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folders.
        /// </summary>
        internal static string FormFolders {
            get {
                return ResourceManager.GetString("FormFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image settings restored.
        /// </summary>
        internal static string ImageSettingsRestored {
            get {
                return ResourceManager.GetString("ImageSettingsRestored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Used Folder.
        /// </summary>
        internal static string label4 {
            get {
                return ResourceManager.GetString("label4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label settings changed.
        /// </summary>
        internal static string LabelSettingsChanged {
            get {
                return ResourceManager.GetString("LabelSettingsChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The LastFolder has not been set correctly.
        /// </summary>
        internal static string LastFolderNotSetCorrectly {
            get {
                return ResourceManager.GetString("LastFolderNotSetCorrectly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add a correct url!!.
        /// </summary>
        internal static string LoginCorrectUrl {
            get {
                return ResourceManager.GetString("LoginCorrectUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect username or password!!.
        /// </summary>
        internal static string LoginError {
            get {
                return ResourceManager.GetString("LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill all information and try again!!.
        /// </summary>
        internal static string LoginReFill {
            get {
                return ResourceManager.GetString("LoginReFill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save to Selected Folder.
        /// </summary>
        internal static string SaveToSelectedFolder {
            get {
                return ResourceManager.GetString("SaveToSelectedFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged in as .
        /// </summary>
        internal static string txtLoggedName {
            get {
                return ResourceManager.GetString("txtLoggedName", resourceCulture);
            }
        }
    }
}
