//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EisenVaultOutlookPlugin {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UserInterfaceStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserInterfaceStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EisenVaultOutlookPlugin.UserInterfaceStrings", typeof(UserInterfaceStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action settings changed.
        /// </summary>
        internal static string ActionSettinsChanged {
            get {
                return ResourceManager.GetString("ActionSettinsChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse Repositories and Select a Folder to Save Email In.
        /// </summary>
        internal static string BrowseFoldersSelectFolder {
            get {
                return ResourceManager.GetString("BrowseFoldersSelectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string btnConfig {
            get {
                return ResourceManager.GetString("btnConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Folder.
        /// </summary>
        internal static string btnCreate {
            get {
                return ResourceManager.GetString("btnCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save to Default Folder.
        /// </summary>
        internal static string btnUploadDefaultFolder {
            get {
                return ResourceManager.GetString("btnUploadDefaultFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save to Last Used Folder.
        /// </summary>
        internal static string btnUploadLastFolder {
            get {
                return ResourceManager.GetString("btnUploadLastFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable &quot;default folder&quot; save button.
        /// </summary>
        internal static string chkDisableDefaultSaveButton {
            get {
                return ResourceManager.GetString("chkDisableDefaultSaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable &quot;last used folder&quot; save button.
        /// </summary>
        internal static string chkDisableLastUsedSaveButton {
            get {
                return ResourceManager.GetString("chkDisableLastUsedSaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable &quot;standard&quot; save button.
        /// </summary>
        internal static string chkDisableStandardSaveButton {
            get {
                return ResourceManager.GetString("chkDisableStandardSaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder Info.
        /// </summary>
        internal static string CreateFoldergroupBox1 {
            get {
                return ResourceManager.GetString("CreateFoldergroupBox1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder Name.
        /// </summary>
        internal static string CreateFolderlabel1 {
            get {
                return ResourceManager.GetString("CreateFolderlabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Folder.
        /// </summary>
        internal static string CreateFolderText {
            get {
                return ResourceManager.GetString("CreateFolderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default folder changed.
        /// </summary>
        internal static string DefaultFolderChanged {
            get {
                return ResourceManager.GetString("DefaultFolderChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The DefaultFolder has not been set correctly.
        /// </summary>
        internal static string DefaultFolderNotSetCorrectly {
            get {
                return ResourceManager.GetString("DefaultFolderNotSetCorrectly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while uploading file, Please try again!!.
        /// </summary>
        internal static string ErrorOnUpload {
            get {
                return ResourceManager.GetString("ErrorOnUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File(s) uploaded successfully.
        /// </summary>
        internal static string FilesUploadedSuccessfully {
            get {
                return ResourceManager.GetString("FilesUploadedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Folder.
        /// </summary>
        internal static string FormConfigbtnCreate {
            get {
                return ResourceManager.GetString("FormConfigbtnCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore Default Images.
        /// </summary>
        internal static string FormConfigbtnRestoreImages {
            get {
                return ResourceManager.GetString("FormConfigbtnRestoreImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string FormConfigbtnSaveImage {
            get {
                return ResourceManager.GetString("FormConfigbtnSaveImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string FormConfigbtnSaveImageLogo {
            get {
                return ResourceManager.GetString("FormConfigbtnSaveImageLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save default folder.
        /// </summary>
        internal static string FormConfigbtnSelectDefaultFolder {
            get {
                return ResourceManager.GetString("FormConfigbtnSelectDefaultFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string FormConfigbtnSelectImage {
            get {
                return ResourceManager.GetString("FormConfigbtnSelectImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string FormConfigbtnSelectImageLogo {
            get {
                return ResourceManager.GetString("FormConfigbtnSelectImageLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label configuration.
        /// </summary>
        internal static string FormConfiggroupBox2 {
            get {
                return ResourceManager.GetString("FormConfiggroupBox2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable / Disable Buttons.
        /// </summary>
        internal static string FormConfigGroupBox3 {
            get {
                return ResourceManager.GetString("FormConfigGroupBox3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        internal static string FormConfiggroupBox5 {
            get {
                return ResourceManager.GetString("FormConfiggroupBox5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon.
        /// </summary>
        internal static string FormConfiggroupBox6 {
            get {
                return ResourceManager.GetString("FormConfiggroupBox6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default upload folder.
        /// </summary>
        internal static string FormConfiglabel1 {
            get {
                return ResourceManager.GetString("FormConfiglabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node Tag.
        /// </summary>
        internal static string FormConfiglabel2 {
            get {
                return ResourceManager.GetString("FormConfiglabel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node Name.
        /// </summary>
        internal static string FormConfiglabel3 {
            get {
                return ResourceManager.GetString("FormConfiglabel3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example Url.
        /// </summary>
        internal static string FormConfigLabel4 {
            get {
                return ResourceManager.GetString("FormConfigLabel4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommended size: 560 x 81.
        /// </summary>
        internal static string FormConfiglabel5 {
            get {
                return ResourceManager.GetString("FormConfiglabel5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommended size: 50 x 50.
        /// </summary>
        internal static string FormConfiglabel6 {
            get {
                return ResourceManager.GetString("FormConfiglabel6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string FormConfigLabel7 {
            get {
                return ResourceManager.GetString("FormConfigLabel7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static string FormConfigTabActions {
            get {
                return ResourceManager.GetString("FormConfigTabActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Folder.
        /// </summary>
        internal static string FormConfigtabDefaultFolder {
            get {
                return ResourceManager.GetString("FormConfigtabDefaultFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.
        /// </summary>
        internal static string FormConfigtabImage {
            get {
                return ResourceManager.GetString("FormConfigtabImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labels.
        /// </summary>
        internal static string FormConfigtabLabels {
            get {
                return ResourceManager.GetString("FormConfigtabLabels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        internal static string FormConfigText {
            get {
                return ResourceManager.GetString("FormConfigText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folders.
        /// </summary>
        internal static string FormFolders {
            get {
                return ResourceManager.GetString("FormFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Folder.
        /// </summary>
        internal static string FormFolderslblTitle {
            get {
                return ResourceManager.GetString("FormFolderslblTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Info.
        /// </summary>
        internal static string groupbox1UserInfo {
            get {
                return ResourceManager.GetString("groupbox1UserInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image settings restored.
        /// </summary>
        internal static string ImageSettingsRestored {
            get {
                return ResourceManager.GetString("ImageSettingsRestored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        internal static string label1UserName {
            get {
                return ResourceManager.GetString("label1UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance URL.
        /// </summary>
        internal static string label3url {
            get {
                return ResourceManager.GetString("label3url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Used Folder.
        /// </summary>
        internal static string label4 {
            get {
                return ResourceManager.GetString("label4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label settings changed.
        /// </summary>
        internal static string LabelSettingsChanged {
            get {
                return ResourceManager.GetString("LabelSettingsChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The LastFolder has not been set correctly.
        /// </summary>
        internal static string LastFolderNotSetCorrectly {
            get {
                return ResourceManager.GetString("LastFolderNotSetCorrectly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add a correct url!!.
        /// </summary>
        internal static string LoginCorrectUrl {
            get {
                return ResourceManager.GetString("LoginCorrectUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect username or password!!.
        /// </summary>
        internal static string LoginError {
            get {
                return ResourceManager.GetString("LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill all information and try again!!.
        /// </summary>
        internal static string LoginReFill {
            get {
                return ResourceManager.GetString("LoginReFill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save to Selected Folder.
        /// </summary>
        internal static string SaveToSelectedFolder {
            get {
                return ResourceManager.GetString("SaveToSelectedFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged in as .
        /// </summary>
        internal static string txtLoggedName {
            get {
                return ResourceManager.GetString("txtLoggedName", resourceCulture);
            }
        }
    }
}
